### ISSUE TITLE
I Think i Have another issue with code 

### ISSUE THREAD

**Issue by mrwhitelab7860** [evmason/py-proxy-checker#3]
I Found an issue with code check line 108 .
 line 108      if port is '':
		         continue

===========================================
When I execute command proxy-checker.py proxy_list.txt

RESULT:
OK proxies: 0
Warning proxies: 0
Bad proxies: 0
Traceback (most recent call last):
  File "test.py", line 159, in <module>
    main()
  File "test.py", line 135, in main
    result_text = proxy_check_result.decode('utf8').strip()
AttributeError: 'bool' object has no attribute 'decode'
